# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = habs_db/migrations

# template used to generate migration file names; during revision
# generate, the heading separator (usually underscore) of the 
# selected template will be used.
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, requires the python-dateutil library.
# timezone =

# max length of characters to use in "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during the 'revision' command,
# regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc files to be created
# sourceless = false

# version location specification; This defaults
# to habs_db/migrations/versions.  When using multiple version
# directories, paths must be separated by spaces,
# commas or colons. Default:
# version_locations = %(here)s/bar %(here)s/bat habs_db/migrations/versions

# version path separator; as mentioned above, this is the character used to split
# version_locations. The default within new projects is 'os.pathsep', which is 
# ';' on windows and ':' on unix.
# version_path_separator = :

# set to 'true' to search source files recursively
# recursive_version_search = false

# the output encoding used when revision files
# are written from script.py.mako
# output_encoding = utf-8

sqlalchemy.url = postgresql://user:pass@localhost/habs


[post_write_hooks]
# post_write_hooks allows scripts to be run after a revision file is generated.
# black example:
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = REVISION_SCRIPT_FILE

[logging]
default_handler = console

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
