"""full_update

Revision ID: 9143d94f242b
Revises: 001_initial_schema
Create Date: 2026-05-16 23:22:04.583336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9143d94f242b'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('otp_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otp_email', 'otp_verifications', ['email'], unique=False)
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('booked', 'completed', 'cancelled', 'no_show', name='appointment_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('appointments', 'sms_reminder_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('doctors', sa.Column('verification_status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('doctors', sa.Column('rejection_reason', sa.Text(), nullable=True))
    
    # Set is_active = False for all existing doctor rows
    op.execute("UPDATE doctors SET is_active = False")

    op.alter_column('doctors', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ml_predictions', 'model_version',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ml_predictions', 'threshold_used',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notifications', 'status',
               existing_type=postgresql.ENUM('pending', 'sent', 'failed', name='notification_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('time_slots', 'is_available',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('users', 'scholarship',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'hypertension',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'diabetes',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'alcoholism',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'has_chronic_condition',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'has_chronic_condition',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'alcoholism',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'diabetes',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'hypertension',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'scholarship',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('users', 'is_email_verified')
    op.alter_column('time_slots', 'is_available',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('notifications', 'status',
               existing_type=postgresql.ENUM('pending', 'sent', 'failed', name='notification_status_enum'),
               server_default=sa.text("'pending'::notification_status_enum"),
               existing_nullable=False)
    op.alter_column('ml_predictions', 'threshold_used',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0.4'::double precision"),
               existing_nullable=False)
    op.alter_column('ml_predictions', 'model_version',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'habs_noshow_v1'::character varying"),
               existing_nullable=False)
    op.alter_column('doctors', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_column('doctors', 'rejection_reason')
    op.drop_column('doctors', 'verification_status')
    op.alter_column('appointments', 'sms_reminder_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('booked', 'completed', 'cancelled', 'no_show', name='appointment_status_enum'),
               server_default=sa.text("'booked'::appointment_status_enum"),
               existing_nullable=False)
    op.drop_index('ix_otp_email', table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_table('admins')
    # ### end Alembic commands ###
